name: Clone Repository and validates web folder
on:
  workflow_dispatch:

jobs:
  webfolder:
    runs-on: ubuntu-latest

    steps:
      - name: Clone or Checkout repository
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.REPO }}

      - name: Check if 'web' folder exists
        run: |
          echo ${{ env.REPO }}
          echo context.repo.owner
          echo context.repo.repo

          if [ -d "web" ]; then
            echo "'web' folder exists."
          else
            echo "'web' folder does not exist."
            exit 1
          fi
